---
- name: Install Nginx
  hosts: webservers
  remote_user: leo
  become: true
  handlers:
    - name: Start nginx
      remote_user: leo
      become: true
      ansible.builtin.command: nginx
    - name: Reload nginx
      become: true
      ansible.builtin.command: nginx -s reload
  tasks:
    - name: NGINX | Install eper-release
      remote_user: leo
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: NGINX | Install Nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: Start nginx
    - name: NGINX | Create general config
      become: true
      remote_user: leo
      ansible.builtin.template:
        src: template/nginx.j2
        dest: /etc/nginx/nginx.conf
        mode: "0755"
      notify: Reload nginx

- name: Install Lighthouse
  hosts: lighthouse
  remote_user: leo
  become: true
  handlers:
    - name: Reload nginx
      become: true
      remote_user: leo
      ansible.builtin.command: nginx -s reload
  pre_tasks:
    - name: Lighthouse | install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  tasks:
    - name: Lighthouse | Copy from git
      become: true
      ansible.builtin.git:
        repo: "https://github.com/VKCOM/lighthouse.git"
        version: master
        dest: "home/leo/lighthouse"
    - name: Lighthouse | Create lighthouse config
      become: true
      ansible.builtin.template:
        src: template/lighthouse.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0755"
      notify: Reload nginx

- name: Install Clickhouse
  hosts: clickhouse
  remote_user: leo
  become: true
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse-common-static distrib
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/rpm/lts/clickhouse-common-static-23.8.9.54.x86_64.rpm
            dest: /home/leo/clickhouse-common-static-23.8.9.54.x86_64.rpm
            mode: "0755"
        - name: Get clickhouse-server distrib
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/rpm/lts/clickhouse-server-23.8.9.54.x86_64.rpm
            dest: /home/leo/clickhouse-server-23.8.9.54.x86_64.rpm
            mode: "0755"
        - name: Get clickhouse-client distrib
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/rpm/lts/clickhouse-client-23.8.9.54.x86_64.rpm
            dest: /home/leo/clickhouse-client-23.8.9.54.x86_64.rpm
            mode: "0755"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-23.8.9.54.x86_64.rpm
          - clickhouse-client-23.8.9.54.x86_64.rpm
          - clickhouse-server-23.8.9.54.x86_64.rpm
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  remote_user: leo
  handlers:
    - name: Start Vector
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: false
        name: vector.service
        state: restarted

  tasks:
    - block:
        - name: Get Vector distrib
          ansible.builtin.get_url:
            url: https://packages.timber.io/vector/0.35.0/vector-0.35.0-1.x86_64.rpm
            dest: /home/leo/vector-0.35.0-1.x86_64.rpm
            mode: "0755"
        - name: Install Vector
          become: true
          remote_user: leo
          ansible.builtin.copy:
            remote_src: true
            src: "/home/leo/"
            dest: "/usr/bin/"
            mode: "0755"
            owner: root
            group: root

        - name: Create Vector directory
          become: true
          ansible.builtin.file:
            path: "/etc/vector"
            state: directory
            mode: "0755"
            owner: root
            group: root

        - name: Vector | Template config
          become: true
          ansible.builtin.template:
            src: template/vector.j2
            dest: /etc/vector/vector.yml
            mode: "0755"
            owner: root
            group: root

        - name: Vector | Create systemd unit
          become: true
          ansible.builtin.template:
            src: template/vector.j2
            dest: /etc/systemd/system/vector.service
            mode: "0755"
            owner: root
            group: root
          notify: Start Vector
