---
# tasks file for lighthouse-role

- name: Lighthouse | install git
  become: true
  remote_user: leo
  ansible.builtin.yum:
    name: git
    state: present
- name: Lighthouse | Copy from git
  become: true
  ansible.builtin.git:
    repo: "https://github.com/VKCOM/lighthouse.git"
    version: master
    dest: "home/leo/lighthouse"
- name: Lighthouse | Create lighthouse config
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0755"
  notify: Reload nginx
