{
 "title": "Dashbord_1",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "1 min"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "5 min"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "15 min"
    }
   ]
  },
  {
   "title": "RAM free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job='nodeexporter'}",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "description": "Free file space",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "free file system space"
    }
   ]
  }
 ]
}